image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - yarn
        script:
          - yarn
          - yarn test
    - step:
        name: Build and deploy stroke
        script:
          - yarn dist
