version: 2.1
orbs:
    node: circleci/node@2.1.1
jobs:
    build_macos:
        macos:
            xcode: '11.4.1'
        steps:
            - checkout
            - node/install:
                install-yarn: true
                node-version: latest
            - run: node --version
            - node/install-packages:
                pkg-manager: yarn
                cache-key: yarn.lock
            - add_ssh_keys:
                fingerprints:
                  - '41:d6:45:5e:9d:51:19:7a:9b:80:6c:8f:30:42:af:ef'
            - run: yarn build
            - run: yarn test
            - run: yarn version --patch --no-git-tag-version
            - run: yarn release
            - run: yarn zip
            - run: yarn upload:zip
            - run: git add package.json
            - run: git commit -m "[skip ci] updated version"
            - run: git push -u origin head
                      
workflows:
    build_macos:
        jobs:
            - build_macos:
                  filters:
                      branches:
                          only: master
