version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build_macos:
    macos:
      xcode: "11.4.1"
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn config set version-sign-git-tag false
            - run: yarn version
            - run: yarn release
            - run: yarn zip
            - run: yarn upload:zip
            - run: git add package.json
            - run: git commit -m "[skip ci] updated version"
            - run: git push
workflows:
    build_macos:
      jobs:
        - build_macos