version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build_macos:
    macos:
      xcode: "11.4.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "41:d6:45:5e:9d:51:19:7a:9b:80:6c:8f:30:42:af:ef"
            - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            - run: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            - run: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            - run: nvm install
            - run: yarn
            - run: yarn build
            - run: yarn version --patch --no-git-tag-version
            - run: yarn release
            - run: yarn zip
            - run: yarn upload:zip
            - run: git add package.json
            - run: git commit -m "[skip ci] updated version"
            - run: git push -u origin head
workflows:
    build_macos:
      jobs:
        - build_macos:
            filters:
              branches:
                only: master