export const FETCH_USER_NOTES_REQUESTED = 'FETCH_USER_NOTES_REQUESTED'
export const FETCH_USER_NOTES_REQUEST_SUCCEEDED = 'FETCH_USER_NOTES_REQUEST_SUCCEEDED'
export const FETCH_USER_NOTES_REQUEST_FAILED = 'FETCH_USER_NOTES_REQUEST_FAILED'

export const SAVE_USER_NOTES_REQUESTED = 'SAVE_USER_NOTES_REQUESTED'
export const SAVE_USER_NOTES_REQUEST_SUCCEEDED = 'SAVE_USER_NOTES_REQUEST_SUCCEEDED'
export const SAVE_USER_NOTES_REQUEST_FAILED = 'SAVE_USER_NOTES_REQUEST_FAILED'

export const QUEUE_USER_NOTES_UPDATE = 'QUEUE_USER_NOTES_UPDATE'
export const CREATE_NEW_USER_NOTE = 'CREATE_NEW_USER_NOTE'

export const ADD_EDITOR_ACTIONS_STROKE = 'ADD_EDITOR_ACTIONS_STROKE'

export const SWITCH_ACTIVE_NOTE = 'SWITCH_ACTIVE_NOTE'
export const SWITCH_ACTIVE_NOTE_SUCCEEDED = 'SWITCH_ACTIVE_NOTE_SUCCEEDED'

export const TRASH_USER_NOTE = 'TRASH_USER_NOTE'
export const TRASH_USER_NOTE_REQUESTED = 'TRASH_USER_NOTE_REQUESTED'
export const TRASH_USER_NOTE_CANCELED = 'TRASH_USER_NOTE_CANCELED'

export const TAGS_REQUESTED = 'TAGS_REQUESTED'
export const TAGS_REQUESTED_SUCCEEDED = 'TAGS_REQUESTED_SUCCEEDED'
export const SET_ACTIVE_TAG = 'SET_ACTIVE_TAG';

export const ROUTE_CHANGED = 'ROUTE_CHANGED'

export const SEARCH_DRAWER_OPENED = 'SEARCH_DRAWER_OPENED'
export const SEARCH_DRAWER_CLOSED = 'SEARCH_DRAWER_CLOSED'